configuration: &configuration
  adapter: postgresql
  encoding: utf-8
  database: emberjs_example_<%= Rails.env %>
  pool: 5
  username: dev
  password: dev

development:
  <<: *configuration

test:
  <<: *configuration

production:
  <<: *configuration
